runtime: python310
entrypoint: gunicorn -b :$PORT url_shortener.wsgi

env_variables:
  CLOUD_SQL_CONNECTION_NAME: 'gauth-423110:asia-east1:yvonne51427-gcp1'
  DB_USER: 'yvonne51427-gcp1'
  DB_PASSWORD: 'GCP2024!Yvonne'
  DB_NAME: 'url_shortener_db'
  DB_HOST: '35.229.182.71'
  DB_PORT: '3307'
  GOOGLE_CLIENT_ID: '1021189136617-03ek9sl4urcg7en6okm6h1ipr468j8at.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: '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'
  FACEBOOK_APP_ID: '411117978506647'
  FACEBOOK_APP_SECRET: '9242675435cf2174a0078872be9489a6'

beta_settings:
  cloud_sql_instances: 'gauth-423110:asia-east1:yvonne51427-gcp1'

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5

handlers:
- url: /static
  static_dir: staticfiles/

- url: /.*
  script: auto
