version: '3.8'

services:
  db:
    image: mariadb:10.5 
    restart: always
    environment:
      MYSQL_DATABASE: url_shortener_db
      MYSQL_USER: url_shortener_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
